export default function Team() {
  return (
    <section id="team">
      <h2>Team</h2>
      <section>
        {/* <!-- Auto Generated by GPT based on Process Document --> */}
        <section>
          <h3>Code Crusaders</h3>
          <section id="CodeCrusaders">
            <div className="team-member">
              <div className="member-photo">
                <img
                  src="https://avatars.githubusercontent.com/u/113440108?v=4&size=64"
                  alt="JP's picture"
                />
              </div>
              <div className="member-info">
                <h2 className="member-name">JP Dumont</h2>
                <h3 className="member-role">
                  Team Lead / Full Stack Developer
                </h3>
                <p className="member-description">
                  JP serves as the primary point of contact within the team,
                  plans meetings, and ensures project progress aligns with
                  objectives.
                </p>
              </div>
            </div>

            <div className="team-member">
              <div className="member-photo">
                <img
                  src="https://avatars.githubusercontent.com/u/70248258?s=64&v=4"
                  alt="Aiden's picture"
                />
              </div>
              <div className="member-info">
                <h2 className="member-name">Aiden Green</h2>
                <h3 className="member-role">Full Stack Developer & Scribe</h3>
                <p className="member-description">
                  Aiden takes notes during meetings and plays a key role in
                  back-end development, focusing on API design and
                  implementation.
                </p>
              </div>
            </div>

            <div className="team-member">
              <div className="member-photo">
                <img
                  src="https://avatars.githubusercontent.com/u/113440108?v=4&size=64"
                  alt="Jessie's picture"
                />
              </div>
              <div className="member-info">
                <h2 className="member-name">Jessie Perce</h2>
                <h3 className="member-role">
                  Full Stack Developer & Sponsor Liaison
                </h3>
                <p className="member-description">
                  Jessie acts as the main communication channel between the team
                  and the sponsor, ensuring clarity in requirements and
                  deliverables.
                </p>
              </div>
            </div>

            <div className="team-member">
              <div className="member-photo">
                <img
                  src="https://avatars.githubusercontent.com/u/113440108?v=4&size=64"
                  alt="Michael's picture"
                />
              </div>
              <div className="member-info">
                <h2 className="member-name">Michael Nersinger</h2>
                <h3 className="member-role">Full Stack Developer</h3>
                <p className="member-description">
                  Michael has a keen understanding for Full Stack Development
                  and aids greatly in the teams success of the application.
                </p>
              </div>
            </div>

            <div className="team-member">
              <div className="member-photo">
                <img
                  src="https://avatars.githubusercontent.com/u/113440108?v=4&size=64"
                  alt="Charlie's picture"
                />
              </div>
              <div className="member-info">
                <h2 className="member-name">Charlie Luebstorff</h2>
                <h3 className="member-role">Full Stack Developer</h3>
                <p className="member-description">
                  Charlie designs and implements the graphical user interface
                  (GUI) of the application, handling all technical details
                  related to the visual features.
                </p>
              </div>
            </div>

            <div className="team-member">
              <div className="member-photo">
                <img
                  src="https://avatars.githubusercontent.com/u/113440108?v=4&size=64"
                  alt="Jacob's picture"
                />
              </div>
              <div className="member-info">
                <h2 className="member-name">Jacob Canedy</h2>
                <h3 className="member-role">
                  Full Stack Developer & Mockup Development
                </h3>
                <p className="member-description">
                  Jacob is responsible for converting the defined requirements
                  into mockups that can be presented to the sponsor for feedback
                  before work begins.
                </p>
              </div>
            </div>

            <div className="team-member">
              <div className="member-photo">
                <img
                  src="https://avatars.githubusercontent.com/u/113440108?v=4&size=64"
                  alt="Huan's picture"
                />
              </div>
              <div className="member-info">
                <h2 className="member-name">Huan Huynh</h2>
                <h3 className="member-role">Test Developer</h3>
                <p className="member-description">
                  Huan is responsible for designing and implementing both
                  front-end UI testing and back-end service testing to ensure
                  product quality.
                </p>
              </div>
            </div>

            <div className="team-member">
              <div className="member-photo">
                <img
                  src="https://avatars.githubusercontent.com/u/113440108?v=4&size=64"
                  alt="Taha's picture"
                />
              </div>
              <div className="member-info">
                <h2 className="member-name">Taha Syed-Quadri</h2>
                <h3 className="member-role">Front-End Developer</h3>
                <p className="member-description">
                  Taha works on the design and implementation of the front-end
                  user interface of the application, focusing on delivering an
                  intuitive visual experience.
                </p>
              </div>
            </div>
          </section>
        </section>
      </section>
      <section>
        <h3>Coach</h3>
        <div className="team-member">
          <div className="member-photo">
            {/* <!-- Placeholder for a photo if desired --> */}
            <img
              src="https://claws.rit.edu/photos/images/placeholder.jpg"
              alt="member picture"
            />
          </div>
          <div className="member-info">
            <h2 className="member-name">Bryan Basham</h2>
            <h3 className="member-role">Coach</h3>
            <h4>bdbvse@rit.edu</h4>
            <p className="member-description">
              Golisano College of Computing and Information Sciences Faculty and
              Software Engineering Senior Project Coach
            </p>
          </div>
        </div>
      </section>
      <section id="sponsor">
        <h2>Sponsor</h2>
        <p>FiTR Skills</p>
      </section>
    </section>
  )
}
